adjectivel = input("Enter an adjective: ")
noun = input("Enter a noun: ")
adjective2 = input("Enter an adjective: ")
verb = input("Enter a verb: ")
adjective3 = input("Enter an adjective: ")

print(f"Today I went to a {adjectivel} zoo. ")
print(f"ln an exhibit, I saw {noun}" )
print(f"{noun} was {adjective2} and {verb}ing")
print(f"l was {adjective3}")
